### ISSUE TITLE
Caching of rented vehicles resulting in the delivery of wrong rented vehicle

### ISSUE THREAD

**Issue by d3rt13n** [mInternauta/AgroSponsor#3]
Ok here goes.

The implements that were rented in a playsession are 'remembered' by the GUI even if not saving the game and starting the same map on an empty gamesave.

So in short if you start a new game on gamesave 1 using any map and you rent a certain vehicle or tool (lets say a Lexion 760) and you exit that game (with or without saving).
You start the same map after deleting the savegame from above if you saved or just selecting the same savegame (in this case 1) and restarting a new game, the rented vehicles from the first unsaved session are still 'remembered' by the Agrosponsor GUI. So in this case the Lexion 760 would be rerented and delivered, even if another item was rented in this new game session. Then if you selected a CASE axionflow combine in this session for example, that one would be delivered. 

If however you would have rented another vehicle after the Lexion 760 in the first session, that one would be delivered second (after the Lexion) and then the Case in the current session.

I hope this is clear. If not, just rent a couple of vehicles and don't save the session, but play the same map using the same gamesave location and you'll catch my drift.

Hope you get this bug sorted, cause this is really a cool mod.  

This happens on every map, whether it's vanilla (Bjornholm) or modded maps.

**Comment by mInternauta** [comment]
I got it =D, Okay. Thank you for reporting this issue. I will examine the code and fix.

**Comment by d3rt13n** [comment]
Alles klar !... and no, thank you for creating this mod. :)

**Comment by mInternauta** [comment]
Okay Its fine, i will make a fix soon. Thank you and keep playing !

Enviada do meu iPhone

Em 05/04/2016, ?s 18:51, "d3rt13n" <notifications@github.com<mailto:notifications@github.com>> escreveu:

Alles klar !... and no, thank you for creating this mod. :)

##

**Comment by mInternauta** [comment]
I'm kind of out of time because of other projects. But soon I will make the correction. There is a temporary solution for the problem:

When deleting a savegame, you must delete also the savegame folder in FS2015 folder:

Windows:
**C: \ Users \ USERNAME \* YOUR \* \ Documents \ My Games \ FarmingSimulator2015**
